container:
  image: rust:latest

test_task:
  registry_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build
  test_script: cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index

# If Cargo.lock is modified on the main branch, make a release.
# TODO: Make this only run if the *version* is changed in Cargo.lock.
release_task:
  only_if: "changesInclude('Cargo.lock') && $BRANCH == 'main' && $CIRRUS_CRON == ''"
  depends_on:
    - test
  env:
    CARGO_REGISTRY_TOKEN: ENCRYPTED[7bd51949c55034d5d16842498f4c88b4e3b463736d31ae8e36bb84fcbebff9c244e11cdec761a45c0a65f49b6d468a4e]
  #  BORK_GITHUB_TOKEN: ENCRYPTED[cc80f90b8db1cbe53aabf4f50bf73331c88ea3e1b5412bb0f7bc264bd233f23bf8df4fc2b4c41f87ec07310d63619801]
  install_script:
    - cargo install cargo-deb cargo-rpm
  build_script:
    - cargo build
  build_deb_script:
    - cargo deb
  build_rpm_script:
    - cargo rpm build
  publish_script:
    - cargo publish
  #github_release_script:
  #  - bork release
